### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by aminaaslam** [ywilkof/spark-jobs-rest-client#3]
Hi,
I am trying to submit a job to my spark cluster stanalone mode through a Java Program. Here is how it looks 
SparkRestClient sparkRestClient = SparkRestClient.builder()
				                          .masterHost("spark://172.16.166.227:6066 ")
	                                                  .sparkVersion("2.0.0")
	                                                   .build();

But it keeps giving me this error. However, my cluster is up and running and i can submit jobs from the command line using the spark-submit script. This is the exception that i am getting.
com.github.ywilkof.sparkrestclient.FailedSparkRequestException: java.net.UnknownHostException: spark: Temporary failure in name resolution
	at com.github.ywilkof.sparkrestclient.HttpRequestUtil.executeHttpMethodAndGetResponse(HttpRequestUtil.java:25)
	at com.github.ywilkof.sparkrestclient.JobSubmitRequestSpecificationImpl.submit(JobSubmitRequestSpecificationImpl.java:154)
	at org.mymanager.ResourceManager.main(ResourceManager.java:19)
Caused by: java.net.UnknownHostException: spark: Temporary failure in name resolution
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:111)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:220)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:164)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:139)
	at com.github.ywilkof.sparkrestclient.HttpRequestUtil.executeHttpMethodAndGetResponse(HttpRequestUtil.java:16)

**Comment by ywilkof** [comment]
Hi @aminaaslam,
in masterHost method pass only the ip or DNS name of the host, without spark:// or the port number appended, so it looks like this:
``` java
.masterHost("172.16.166.227")
```
you can pass the port in the masterPort() builder method, though in your case it is unnecessary as you are using the default 6066 port. 

Hope this helps.

**Comment by ywilkof** [comment]
@aminaaslam did this solve your UnknownHostException exception?

**Comment by aminaaslam** [comment]
Yes i was able to solve and it working fine. But my application fails to run on the spark cluster when i am sending different spark related parameters with my job for which i have raised another issue. It would be very helpful if you look at the.
